# Dockerfile.backend
FROM python:3.10-slim

WORKDIR /app

# Copia apenas requirements para aproveitar cache
COPY requirements.txt .

# Instala dependências + driver Mongo (motor)
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install motor

# Copia todo o código
COPY . .

# Expondo FastAPI com reload para dev
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"] 